### ISSUE TITLE
make: *** [makefile:6: SLK_img2pix] Error 1 in Linux

### ISSUE THREAD

**Issue by eGax** [Captain4LK/SoftLK-tools#1]
Greetings. I'm having an issue building img2pixel on Manjaro Linux (Arch-based distro). I've successfully built and installed SoftLK-lib without issue. Attempting to build img2pixel:
`git clone https://github.com/Captain4LK/SoftLK-tools.git`
`cd SoftLK-tools/SLK_img2pixel/bin/unix/`
`make`

Results in this error: `make: *** [makefile:6: SLK_img2pix] Error 1`

That line 6 of the makefile in question is: `$(CC) -o SLK_img2pix $^ $(CFLAGS)`

Here is the terminal build log: [img2pixel_terminalbuildlog.txt](https://github.com/Captain4LK/SoftLK-tools/files/6779193/img2pixel_terminalbuildlog.txt)

You will see many `undefined reference to SLK_gui_####` messages before it fails.
I have the build dependencies installed and have built this a few months ago without issues and I'm not sure what is going on now. My current specs are Manjaro Linux KDE stable branch, Ryzen 3900x 12-core, and gcc version 11.1.0 (GCC).

I know GCC versions 10+ are stricter than the previous versions, but I'm not sure if this has anything to do with this issue.

**Comment by Captain4LK** [comment]
Are you using the newest version of libSLK? I made some changes to (theoretically) make compiling easier in both libSLK and SLK_img2pixel (no more submodules, libSLK_gui is now included in libSLK.a). 

If you are sure that you compiled the newest version of libSLK, could you provide the output of this command:

``whereis -B $(ldconfig -v 2>/dev/null | grep -v ^$'\t' | cut -f1 -d":" | tr "\n" " ") -f libSLK.a``

(This bash command searches for all locations of libSLK.a in the directories the linker looks at)

**Comment by eGax** [comment]
Well, I built and installed libSLK from GitHub minutes before I tried to build img2pixel.

`~]$ whereis -B $(ldconfig -v 2>/dev/null | grep -v ^$'\t' | cut -f1 -d":" | tr "\n" " ") -f libSLK.a`
`libSLK.a: /usr/lib/libSLK.a`

Installing the new build over the old one should be OK, no?

**Comment by eGax** [comment]
Ah, you know what, could it be due to still having `/lib/libSLK_gui.a` from previous builds? I will try to delete and see if that makes it better.

**Comment by eGax** [comment]
I removed:
`/lib/libSLK.a`
`/lib/libSLK_gui.a`

Then rebuilt libSLK followed by img2pixel and it built fine.

Thank you for letting me know there are no longer any submodules.
