### ISSUE TITLE
Request drag & drop functionality back from 1.4 builds in the 1.5+ builds if possible.

### ISSUE THREAD

**Issue by eGax** [Captain4LK/SoftLK-tools#10]
How it worked before the 1.5 rewrite.

https://github.com/user-attachments/assets/bc98f451-7096-4d72-b5ad-8809b662acf3

How it is currently.

https://github.com/user-attachments/assets/af9df333-c9c0-4ba0-ab6b-ed9f1b6f4695

**Comment by Captain4LK** [comment]
The drag'n'drop functionality was restored in 6771bdcb0b247ea616765c59781120d7044aef64

**Comment by eGax** [comment]
Looks good and working as before. Thank you.
