### ISSUE TITLE
img2pixel gui seems to not like texture names with multiple periods when batching converting images.

### ISSUE THREAD

**Issue by eGax** [Captain4LK/SoftLK-tools#5]
img2pixel seems to not like texture names with multiple periods in them when batch converting whole directories. I have a dir with files named like this:

```
st.tms[0].png
st.tms[1].png
st.tms[2].png
st.tms[3].png
st.tms[4].png
st.tms[5].png
```

Writing them to a sub-DIR named slk. It seems to be treating the 1st period as the end of file, writes 1 file converted and correct, then writes a transparent 1x1 pixel file named `slk.png` then seems to fail to write anything else after because I think it sees it as the same name(my best guess).

This is in Linux.

**Comment by eGax** [comment]
If I rename them to remove the period and brackets, it works as normal, but still writes a texture named slk.png 1x1 in dimensions for some reason.

**Comment by Captain4LK** [comment]
Yeah, the directory handling has always been funky. I originally used a library for handling directories/path out of convenience (differences between windows and pretty much every other operating system under the sun...), but it doesn't work properly. 

I'll rework the path/directory handling soon (this week).

**Comment by Captain4LK** [comment]
The latest commit 60e77cf5aacc6d03de1deaacbcc9589f465ff993 should fix the problem

**Comment by eGax** [comment]
Ok, I will compile the next time I am home and give a try. Thanks.

**Comment by eGax** [comment]
OK, finally got to checking this fix out. You have fixed the bigger issue with the periods and naming.

There are still a few lower priority 2 issues working together to write a single empty PNG after the name of the DIR you pick for export, but I will make a new issue for that.
