### ISSUE TITLE
Feature Request: Generalize image sizes

### ISSUE THREAD

**Issue by jauntyjocularjay** [Captain4LK/SoftLK-tools#6]
It would be very handy to not have to cut my images into squares and then re-stitch them together.

Currently my rectangles are being output as squares when I run them through the application.

**Comment by Captain4LK** [comment]
You should be able to change the image width and height independently in the **Sample** tab. Alternatively you can select the **Relative** mode, which divides the image size by **x div** and **y div**

Or am I misunderstanding your problem?

**Comment by eGax** [comment]
Yes, you can set them to any size you wish, not just squares.

![image](https://github.com/Captain4LK/SoftLK-tools/assets/9817245/67f56846-542f-4217-b73a-4ff5a9e2b555)

**Comment by jauntyjocularjay** [comment]
Ah, my mistake! Thank you!
