### ISSUE TITLE
Missing batch conversion options in load menu in current GUI

### ISSUE THREAD

**Issue by eGax** [Captain4LK/SoftLK-tools#7]
I am giving the AppImage a try in Manjaro Linux KDE/Plasma before I tried to build it myself. The UI is missing the folder batch option the previous versions had. This is powerful and super handy to batch like images with your custom presets.

 Where they were in the load menu.
 
![image](https://github.com/user-attachments/assets/c4a630cb-8154-4a8e-833d-43786a128464)

The load menu has been shorted to this.

![image](https://github.com/user-attachments/assets/ce6a2d88-ff75-46da-9afa-a8613f69e38a)

I did look around to see if they got moved, but they do appear to have been removed?

https://github.com/user-attachments/assets/a65193a5-2752-48e2-9625-7521d251fa1a

If so, any plans to bring them back in? This makes converting a batch of images much slower. Even just adding them in another menu named **Batch** or batch conversion to the right would be great.

![image](https://github.com/user-attachments/assets/5f101e21-d732-4955-9d03-562a35ffbdef)

Thank you for your work!

**Comment by Captain4LK** [comment]
img2pixel 1.5 was basically a complete rewrite, and I've forgotten about some features during its development.

My original plan was to wait until sdl3 is released, since that would allow me to finally get rid of the remaining windows specific code. I'll try to re-implement it in the next few days.

**Comment by eGax** [comment]
Appreciate it!

Doing individual textures is great but once you have a preset locked in, it is so quick to batch many image/texture sets at a time.

**Comment by Captain4LK** [comment]
I've pushed an initial implementation of the batch feature. It can be found in the tools section of the menu bar.

New features include a progress indicator and the option to select the file type of the processed images.

**Comment by eGax** [comment]
It is working well. I like the option for a PCX 8 paletted image format. As it is currently it seems to work well. Having it in its own section is good and gives a space for any other future additions like this that may be thought up but don't get in the way of the main app focus.

**Comment by eGax** [comment]
A few initial thoughts. Could it be possible to make it remember last dir opened as the main file dialog for opening images, pallettes, and setting does?

**Comment by Captain4LK** [comment]
It was intended to remember the last path, I just forgot to actually keep track of it. Should be fixed in 8e24e31a4ebd0d1bc075cea4592cbc3fb5a5280b

**Comment by eGax** [comment]
Yes, thank you!
