### ISSUE TITLE
Requesting pcx export for SLK_img2pixel GUI version also.

### ISSUE THREAD

**Issue by eGax** [Captain4LK/SoftLK-tools#8]
This would be useful in the GUI version as well, as it probably is in the cmd version. I work with PCX when dealing with palletized images more than any other format.

**Comment by Captain4LK** [comment]
img2pixel already supports pcx export, but I think it was added after I've compiled the current appimage on itch.
However, the file type entry during file dialog creation was wrong, but that's fixed now.

**Comment by eGax** [comment]
Yes, that's why I didn't see it an option, awesome! Thank you. I'm setting up to build your current commits here soon.

**Comment by eGax** [comment]
Looks good on my end, seems to be working now. Thanks!
