### ISSUE TITLE
Current build no longer automatically loads your default.json settings.

### ISSUE THREAD

**Issue by eGax** [Captain4LK/SoftLK-tools#9]
This worked prior to 1.5 versions. This doesn't work with the AppImage, assumed it was due to that.

I built it myself on Manjaro Linux KDE/Plasma to make use of my preferred kdialog file dialog anyway and tried to see if it would load my default.json, and it still doesn't seem to work. As before, my default.json is stored in the same DIR right next to the img2pixel executable. The json seems valid because I can load it from the img2pixel menu and loads fine with all my setting intact.

**Comment by Captain4LK** [comment]
Should be fixed in 7fb02d50519b343e9f2546be8859cb11d85db7c7

img2pixel 1.5 was basically a complete rewrite, and I've forgotten about some features during it's development.

**Comment by eGax** [comment]
I thought that might have been the case. I really didn't like the new GUI when I 1st tried it early on, and just came back to it to give it another try and noticed a few features missing from 1.4 versions.

I appreciate you, thanks for such a great tool. I sing its praises frequently across discords; Map-Center, Quake Mapping, others, etc.

**Comment by eGax** [comment]
Excellent, you have restored functionality of default.json loading by default. 🙌🏼 Thank you.
